'use strict';
module.exports = {
  SHOW_ALL_ACTIVITIES: 'SHOW_ALL_ACTIVITIES',
  SHOW_MY_ACTIVITIES: 'SHOW_MY_ACTIVITIES',
  REGISTER: 'REGISTER',
  SIGN_UP_TO_ACTIVITY: 'SIGN_UP_TO_ACTIVITY',
  CONFIRM_SIGN_UP_TO_ACTIVITY: 'CONFIRM_SIGN_UP_TO_ACTIVITY',
  DECLINE_SIGN_UP_TO_ACTIVITY: 'DECLINE_SIGN_UP_TO_ACTIVITY',
};
